<a href="https://colab.research.google.com/github/Iver71/Generative-IA/blob/main/Credit_Scoring_Give_Me_Some_Credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Give Me Some Credit Dataset
###Contexto:
En las economías de mercado, los bancos desempeñan un rol fundamental al determinar el acceso al financiamiento y las condiciones bajo las cuales este se otorga. Estas decisiones influyen directamente en la capacidad de inversión de individuos y empresas, siendo el crédito un elemento clave para el correcto funcionamiento del sistema económico.

En este contexto, los modelos de credit scoring se utilizan para estimar la probabilidad de incumplimiento de un prestatario. Estos modelos permiten a las instituciones financieras evaluar el riesgo asociado a la concesión de un crédito, facilitando la toma de decisiones informadas.

El presente proyecto se enmarca en la mejora de estos modelos, mediante la predicción de la probabilidad de que un individuo experimente dificultades financieras en un horizonte de dos años. Para ello, se dispone de un conjunto de datos históricos correspondiente a aproximadamente 250,000 prestatarios, el cual incluye variables relacionadas con el comportamiento crediticio, nivel de endeudamiento e ingresos.

El objetivo principal es desarrollar un modelo predictivo que contribuya a una mejor evaluación del riesgo crediticio y que, potencialmente, pueda ser utilizado tanto por entidades financieras como por los propios individuos para optimizar la toma de decisiones financieras.

####Links:
[Enlace del kaggle](https://www.kaggle.com/competitions/GiveMeSomeCredit/data)

[Enlace de la data](https://github.com/DrIanGregory/Kaggle-GiveMeSomeCredit/tree/master/data)

##Descripcion de Variables
**RevolvingUtilizationOfUnsecuredLines:** Proporción del saldo usado en tarjetas y líneas de crédito sin garantía respecto al límite total disponible.

**age:** Edad del prestatario en años.

**NumberOfTime30-59DaysPastDueNotWorse:** Número de veces que el cliente tuvo retrasos de 30 a 59 días en los últimos 2 años.

**DebtRatio:** Relación entre las deudas mensuales totales y el ingreso bruto mensual.

**MonthlyIncome:** Ingreso mensual del cliente.

**NumberOfOpenCreditLinesAndLoans:** Número total de créditos abiertos, incluyendo préstamos y líneas de crédito.

**NumberOfTimes90DaysLate:** Número de veces que el cliente tuvo retrasos de 90 días o más.

**NumberRealEstateLoansOrLines:** Número de préstamos hipotecarios y créditos relacionados a bienes raíces.

**NumberOfTime60-89DaysPastDueNotWorse:** Número de veces que el cliente tuvo retrasos de 60 a 89 días en los últimos 2 años.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = '/content/drive/MyDrive/Data Science Maestría/GiveMeSomeCredit-training.csv'

In [ ]:
import pandas as pd

df = pd.read_csv(path)
df.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [ ]:
df.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [ ]:
df = df.drop(columns = ["Unnamed: 0"])
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0